services:
  bimarz-website:
    image: registry-b9200d2040-azta.apps.ir-central1.arvancaas.ir/bimarz-website:latest
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - media_data:/app/media
    networks:
      - azta-network
      - bimarz-network

  mongodb:
    image: docker.arvancloud.ir/mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - azta-network
      - bimarz-network

volumes:
  mongodb_data:
  media_data:

networks:
  bimarz-network:
  azta-network:
    external: true
